"""
Constants related to the frame and the game
"""

GROUND_HEIGHT = 2

# TODO: should be based on terminal height
FRAME_WIDTH = 170
FRAME_HEIGHT = 40
FRAME_X_VELOCITY = 10
FRAME_RATE = 25
FRAME_LEFT_BOUNDARY = 10
# enemies can spawn in this region
FRAME_RIGHT_BOUNARY = FRAME_WIDTH - 40
FRAME_SPAWN_OFFSET = 20
FRAME_SPAWN_X = FRAME_RIGHT_BOUNARY + FRAME_SPAWN_OFFSET
FRAME_BOTTOM_BOUNDARY = FRAME_HEIGHT - GROUND_HEIGHT - 1

FRAME_MOVE_SPEED = 2

GRAVITY_ACC = 0.15

LASER_VEL = 2

COIN_VALUE = 1

FIREBEAM_LENGTH = 5

DEBUG = True
